---
# Ansible variables for system setup

# Package lists
core_packages_file: "{{ lookup('env', 'HOME') }}/.dotfiles/pkglist.txt"
optional_packages_file: "{{ lookup('env', 'HOME') }}/.dotfiles/pkglist-optional.txt"

# User systemd services to enable
user_services:
  - cameractrlsd.service
  - tailscale-systray.service
