add_newline = false
command_timeout = 200
format = "$hostname${custom.shpool}[$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[✖](bold red) "
success_symbol = "[❯](bold white)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
read_only = " "
read_only_style = "bold yellow"
use_logical_path = false

[git_branch]
format = "[$branch]($style) "
style = "italic white"

[git_status]
format     = '([\[](white)[$all_status]($style)[\]](white) )'
style      = "green"
# ahead      = "⇡${count} "
# diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
# behind     = "⇣${count} "
conflicted = "="
up_to_date = ""
untracked  = "?"
modified   = "!"
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[hostname]
format = '[$ssh_symbol$hostname]($style) : '
ssh_symbol = "⌁ "


[custom.shpool]
description = "Shpool Session Name & Host"
# Only show if inside a shpool session
when = 'test -n "$SHPOOL_SESSION_NAME"'
# Output format: "session_name @ hostname"
command = 'echo "$SHPOOL_SESSION_NAME @ $(hostname)"'
format = '[$symbol$output]($style) : '
symbol = "∞ "
style = "bold purple"
